[package]
authors = ["Lyssieth <raxixor@rax.ee>"]
description = "API for searching for the original source of images."
edition = "2018"
license = "MIT"
name = "sauce-api"
repository = "https://github.com/lyssieth/sauce-api"
version = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
reqwest = {version = "0.10", features = ["json"]}
select = "0.5"
serde = "1.0"
serde_derive = "1.0"
strfmt = "0.1"
urlencoding = "1.1"
